### ISSUE TITLE
1cak.sh error line 79

### ISSUE THREAD

**Issue by hillz1** [gojigeje/openwrt-twitterbot#1]
plugin 1cak.sh error mas "line 79: twit_icak_main: command not found"

**Comment by gojigeje** [comment]
Halo, maaf di kode sepertinya tidak ada kok plugin yang icak -- pakai hufui "i", harusnya 1cak.
sudah diteliti lagi? mungkin ada typo di script kamu @hillz1 ?

edit: sudah saya cek barusan dan normal, sepertinya typo di script kamu..
