### ISSUE TITLE
request fitur twit.py: kirim gambar di DM

### ISSUE THREAD

**Issue by rikza7x** [gojigeje/openwrt-twitterbot#2]
Mantap mas repo nya. terutama script twit.py sangat membantu dan fleksibel sekali.
Namun untuk kirim gambar di DM tidak bisa ya? selalu eror:
`Error: opsi -i hanya bisa digunakan dengan opsi -s saja`

Mungkin kedepannya fitur ini bisa ditambahkan. terima kasih!

**Comment by gojigeje** [comment]
Terima kasih apresiasinya :smile: 
Sayangnya, saat ini pada endpoint api twitter untuk direct message tidak menyediakan fitur untuk menyertakan image saat mengirim dm.

Sumber: 
http://stackoverflow.com/questions/25872420
https://twittercommunity.com/t/uploading-images-in-dms/12317/2

Jadi fitur ini belum bisa ditambahkan, sementara saya close dulu, nanti entah kapan kalau di api twitternya sudah ada fitur tersebut, bisa diopen lagi issue nya :grin:
